// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationMode } from "../CollaborationMode.js";

/**
 * EXPERIMENTAL - collaboration mode presets response.
 */
export type CollaborationModeListResponse = { data: Array<CollaborationMode> };
