// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "../ContentBlock.js";
import type { JsonValue } from "../serde_json/JsonValue.js";

export type McpToolCallResult = {
  content: Array<ContentBlock>;
  structuredContent: JsonValue | null;
};
