// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings.js";

/**
 * Collaboration mode for a Codex session.
 */
export type CollaborationMode =
  | ({ mode: "plan" } & Settings)
  | ({ mode: "pairprogramming" } & Settings)
  | ({ mode: "execute" } & Settings)
  | ({ mode: "custom" } & Settings);
