// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioContent } from "./AudioContent.js";
import type { EmbeddedResource } from "./EmbeddedResource.js";
import type { ImageContent } from "./ImageContent.js";
import type { ResourceLink } from "./ResourceLink.js";
import type { TextContent } from "./TextContent.js";

export type ContentBlock =
  | TextContent
  | ImageContent
  | AudioContent
  | ResourceLink
  | EmbeddedResource;
