// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolAnnotations } from "./ToolAnnotations.js";
import type { ToolInputSchema } from "./ToolInputSchema.js";
import type { ToolOutputSchema } from "./ToolOutputSchema.js";

/**
 * Definition for a tool the client can call.
 */
export type Tool = {
  annotations?: ToolAnnotations;
  description?: string;
  inputSchema: ToolInputSchema;
  name: string;
  outputSchema?: ToolOutputSchema;
  title?: string;
};
