// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessageItem } from "./AgentMessageItem.js";
import type { ReasoningItem } from "./ReasoningItem.js";
import type { UserMessageItem } from "./UserMessageItem.js";
import type { WebSearchItem } from "./WebSearchItem.js";

export type TurnItem =
  | ({ type: "UserMessage" } & UserMessageItem)
  | ({ type: "AgentMessage" } & AgentMessageItem)
  | ({ type: "Reasoning" } & ReasoningItem)
  | ({ type: "WebSearch" } & WebSearchItem);
